import { BrdAnalysis } from '@/types/analysis';

export function exportToMarkdown(analysis: BrdAnalysis): string {
  const date = new Date(analysis.createdAt).toLocaleDateString('vi-VN', {
    year: 'numeric', month: 'long', day: 'numeric',
  });

  const priorityEmoji = {
    critical: '🔴',
    important: '🟡',
    'nice-to-have': '🟢',
  };

  const categoryLabel = {
    'business-logic': 'Business Logic',
    'technical-constraints': 'Technical Constraints',
    nfr: 'Non-Functional Requirements',
    integrations: 'Integrations',
  };

  const questionsByCategory = analysis.questions.reduce(
    (acc, q) => {
      if (!acc[q.category]) acc[q.category] = [];
      acc[q.category].push(q);
      return acc;
    },
    {} as Record<string, typeof analysis.questions[0][]>
  );

  const categoryOrder: (keyof typeof categoryLabel)[] = [
    'business-logic', 'technical-constraints', 'nfr', 'integrations',
  ];

  const questionsSection = categoryOrder
    .filter((cat) => questionsByCategory[cat]?.length)
    .map((cat) => {
      const questions = questionsByCategory[cat]
        .sort((a, b) => {
          const order = { critical: 0, important: 1, 'nice-to-have': 2 };
          return order[a.priority] - order[b.priority];
        });

      const rows = questions
        .map((q) =>
          [
            `### ${priorityEmoji[q.priority]} ${q.id}: ${q.question}`,
            `**Priority:** ${q.priority.charAt(0).toUpperCase() + q.priority.slice(1)}`,
            q.relatedQuote ? `**BRD Reference:** > ${q.relatedQuote}` : '',
            `**Rationale:** ${q.rationale}`,
          ]
            .filter(Boolean)
            .join('\n\n')
        )
        .join('\n\n---\n\n');

      return `## ${categoryLabel[cat]}\n\n${rows}`;
    })
    .join('\n\n');

  const ambiguitiesSection = analysis.ambiguities.length > 0
    ? `## Identified Ambiguities\n\n${analysis.ambiguities
        .map((a) => `- **[${a.id}]** ${a.issue}\n  > "${a.quote}"`)
        .join('\n\n')}`
    : '';

  return `# Stakeholder Questions: ${analysis.title}

**Generated:** ${date}
**Total Questions:** ${analysis.questions.length}
**Critical:** ${analysis.questions.filter(q => q.priority === 'critical').length} | **Important:** ${analysis.questions.filter(q => q.priority === 'important').length} | **Nice-to-have:** ${analysis.questions.filter(q => q.priority === 'nice-to-have').length}

---

## BRD Summary

**Scope:** ${analysis.summary.scope}

**Actors/Stakeholders:** ${analysis.summary.actors.join(', ') || 'Not specified'}

**Key Business Rules:**
${analysis.summary.businessRules.map(r => `- ${r}`).join('\n') || '- Not identified'}

**External Integrations:**
${analysis.summary.integrations.map(i => `- ${i}`).join('\n') || '- None mentioned'}

---

${questionsSection}

${ambiguitiesSection}

---
*Generated by SA Smartie*
`;
}
